version: '3.4'
services:
  app: &app
    build: 
      context: .
      dockerfile: Dockerfile
    tmpfs:
      - /tmp
  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
    volumes:
      - .:/myapp:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    depends_on:
      - db
      - redis
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3001:3001'
      - '3002:3002'
  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - '3000:3000'
  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6370
  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
volumes:
  bundle:
  mysql_data:
  rails_cache:
  node_modules:
  packs:
  redis:
